config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get "sing_up", to: "registrations#new"
  post "sing_up", to: "registrations#create"
  get "sing_in", to: "sessions#new"
  post "sing_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "logout", to: "sessions#destroy"
  get "add", to: "product#new"
  post "add", to: "product#create"
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :number, presence: true, length: {minimum: 11, maximum: 11}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
	def current_user
		@current_user ||=  User.find_by(id: session[:id]) if session[:id].present?
	end
	def user_singed_in?
		current_user.present?
	end
	helper_method :current_user, :user_singed_in?
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: %i[ create ]
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Корзина удалена" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/concerns/current_cart.rb
 module CurrentCart
 	extend ActiveSupport::Concern
 	private
 	def set_cart
 		@cart = Cart.find(session[:cart_id])
 	rescue ActiveRecord::RecordNotFound
 		@cart = Cart.create
 		session[:cart_id] = @cart.id
 	end
 end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: %i[ create ]
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.line_items.build(product: product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to line_item_url(@line_item), notice: "Товар добавлен в корзину." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
		@user = User.find_by(id: session[:id])
		@product = Product.all
	end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		@product.save!
		redirect_to root_path
	end

	private
	def product_params
		params.require(:product).permit(:name, :description, :cost, :image)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
            @user.status = "user"
			session[:id] = @user.id
			redirect_to root_path
		else
      		redirect_to sing_up_path
      		flash[:alert] = 'Неправильно'
		end
	end
	private def user_params
		params.require(:user).permit(:number, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
		session[:id] = nil
		redirect_to root_path
	end
	def new
	end
	def create
		user = User.find_by(number: params[:number] .downcase)
		if user.present? && user.authenticate(params[:password])
			session[:id] = user.id
			redirect_to root_path
		else
			redirect_to sing_in_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<ul>
<% @cart.line_items.each do |item| %>
  <li><%= item.product.name %> </li>
  <%end%>
</ul>

<div>
  <%= button_to "Совершить заказ", @cart, method: :delete %> |

  <%= button_to "Удалить корзину", @cart, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer>
    Создано студентом ДПК Богомазовым Александром Сергеевичем
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Хлеб Хлебов", root_path, :method => :get, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_singed_in? %>
      <li class="nav-item">
    <%= link_to "#{current_user.number}", logout_path, class:"nav-link", :method => :delete%>
      </li>
      <li class="nav-item">
    <%= link_to "Корзина", carts_path(session[:cart_id]), class:"nav-link", :method => :show%>
      </li>
      <%else%>
        <li class="nav-item active">
        <%=link_to "Зарегистрироваться", sing_up_path, class:"nav-link", :method => :get%>
      </li>
      <li class="nav-item">
        <%=link_to "Войти", sing_in_path, class:"nav-link", :method => :get%>
      </li>
    <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Хлебов</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
    </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div id="<%= dom_id line_item %>">
  <p>
    <strong>Product:</strong>
    <%= line_item.product_id %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= line_item.cart_id %>
  </p>

</div>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

app/views/main/index.html.erb
<div class="container mt-5 mb-5">
	<% @product.each do |product|%>
		<div class="d-flex justify-content-center row">
        <div class="col-md-10">
            <div class="row p-2 bg-white border rounded">
               <div class="col-md-3 mt-1"><%= image_tag(product.image.url, :class =>
					"img-fluid img-responsive rounded product-image" )%></div>
                <div class="col-md-6 mt-1">
                    <h5><%=product.name%></h5>
                    <p class="text-justify text-truncate para mb-0"><%=product.description %><br><br></p>
                </div>
                <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                    <div class="d-flex flex-row align-items-center">
                        <h4 class="mr-1"><%=product.cost%> руб.</h4><span class="strike-text"><%=product.cost*2%> руб.</span>
                    </div>
                    <h6 class="text-success">Расспродажа!</h6>
                    <%if user_singed_in?%>
                    <div class="d-flex flex-column mt-4"><%=button_to "Добавить в корзину", line_items_path(product_id: product), class: "btn btn-outline-primary btn-sm mt-2"%></div>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
	<%end%>
    <%if user_singed_in? and @user.status == "admin"%>
 <div class="d-flex flex-column mt-4"><%=button_to "Добавить товар", add_path, class: "btn btn-outline-primary btn-sm mt-2", :method => :get%></div>
<%end%>
</div>

app/views/main/korzina.html.erb
<% @tovars.each do |korzina|%>
	<hr>
	<div class="cartinka"><%= image_tag("#{korzina.tovar_id}.jpeg",style: 'height:15vw;width:15vw') %>
		<div>
	<div class="infa"><div class="ne_infa">
		<h3><%= korzina.name%></h3>
		<p><%= korzina.jpisanie%></p></div>
		<div class="cost">
		<h4>Стоимость: <%=korzina.cost%></h4></div>
	</div>
	<div class="knopka" align="right"><%= link_to "Убрать из корзины", :method => :delete%></div>
	<hr>
<%end%>

app/views/product/new.html.erb
<center>
	<%= form_for @product, :html => {multipart: true}, url: add_path do |form| %>
		<% if @product.errors.any? %>
			<div class = "alert alert-danger">
				<% @product.errors.full_messages.each do |message| %>
					<div><%= message %></div>
				<% end %>
			</div>
		<% end %>
	<p>
		<div class="col-md-3">
			<%= form.label :Название %>
			<%= form.text_field :name, class: "form-control"%>
		</div>
	</p>
	<p>
		<div class="col-md-3">
			<%= form.label :Описание %>
			<%= form.text_field :description, class: "form-control"%>
		</div>
	</p>
	<p>
		<div class="col-md-3">
			<%= form.label :Стоимость %>
			<%= form.number_field :cost, class: "form-control"%>
		</div>
	</p>
	<p>
		<div class="col-md-3">
			<%= form.label :Изображение %>
			<%= form.file_field :image, class: "form-control"%>
		</div>
	</p>
	<p>
		<div class="col-md-3">
			<%= form.submit "Добавить", class: "btn btn-outline-success"%>
		</div>
	</p>
	<% end %>
</center>